baseurl                  = "https://chux0519.github.io/"           # Your domain name. Must end with "/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
isMultilingual           = false
title                    = "chux0519"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    favicon              = "hexyoungs.ico"
    homepage             = "/"                           # What to call the home page link
    footerText           = "chux0519"

# Metadata for Open Graph and Twitter
    description          = "Coding.."               # Max 160 characters show in search results
    images               = ["hexyoungs.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "chux0519"

[[params.mainMenu]]
    link = "/posts"
    text = "文章"

[[params.mainMenu]]
    link = "/tags"
    text = "标签"

[imaging]
    quality = 75
